tokenAddresses:
  hardhat:
    chainlinkFeedRegistry: "0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf"
    usdAddress: "0x0000000000000000000000000000000000000348"
    assets:
      DAI:
        name: "Dai"
        address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
        oracleAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
        whale: "0x2c8fbb630289363ac80705a1a61273f76fd5a161"
        collateralRate: "0.8"
        oracleName: "DAI"
        decimals: 18
      USDC:
        name: "USD Coin"
        address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
        oracleAddress: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
        whale: "0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503"
        collateralRate: "0.8"
        oracleName: "USDC"
        decimals: 6
      USDT:
        name: "Tether"
        address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        oracleAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        whale: "0x5754284f345afc66a98fbb0a0afe71e0f007b949"
        collateralRate: "0.8"
        oracleName: "USDT"
        decimals: 6
      WETH:
        name: "Wrapped ETH"
        address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
        oracleAddress: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
        collateralRate: "0.8"
        oracleName: "ETH"
        decimals: 18
  rinkeby:
    mockedExactlyOracle: "0x05cCA0e6b4C53eC73B28313745641940E5634842"
    multisigAddress: "0x0820289Cb202DbF23B709D4AC1a346331cd590c4"
    assets:
      DAI:
        name: "Dai"
        address: "0x95b58a6bff3d14b7db2f5cb5f0ad413dc2940658"
        oracleAddress: "0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea"
        collateralRate: "0.8"
        oracleName: "DAI"
        decimals: 18
      WETH:
        name: "Wrapped ETH"
        address: "0xc778417e063141139fce010982780140aa0cd5ab"
        oracleAddress: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
        collateralRate: "0.8"
        oracleName: "ETH"
        decimals: 18
  kovan:
      chainlinkFeedRegistry: "0xAa7F6f7f507457a1EE157fE97F6c7DB2BEec5cD0"
      usdAddress: "0x0000000000000000000000000000000000000348"
      assets:
        DAI:
          name: "Dai"
          address: "0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa"
          oracleAddress: "0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa"
          collateralRate: "0.8"
          oracleName: "DAI"
          decimals: 18
        WETH:
          name: "Wrapped ETH"
          address: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
          oracleAddress: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          collateralRate: "0.8"
          oracleName: "ETH"
          decimals: 18
minTimelockDelay: 60
