[profile.default]
solc = '0.8.17'
optimizer = true
optimizer_runs = 200

ffi = true
src = 'test/solidity'
out = 'artifacts/.foundry'
cache_path = 'cache/.foundry'
verbosity = 3

[profile.production.fuzz]
runs = 66_666

[profile.overkill.fuzz]
runs = 6_666_666
